// <auto-generated />
namespace Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class New : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New));
        
        string IMigrationMetadata.Id
        {
            get { return "201210030255552_New"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
